### ISSUE TITLE
Revert evaluating full requestContextInterval

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#37]
See https://github.com/moira-alert/worker/commit/e57ea9562ae96fe2c410f91a36bc096c8ce44a33 and especially https://github.com/moira-alert/worker/commit/e57ea9562ae96fe2c410f91a36bc096c8ce44a33#diff-ad6e777f8d2acc24d503350da3faefe5R134.

After some investigation I came to believe that adding an extra bucket at the end of timeseries is a mistake.

Consider two metrics with names `cpu1`, `cpu2` and function `movingAverage(cpu*, '3min', 'min')`. Let's say that `cpu1` sends points several seconds earlier than `cpu2`. At some point in time the timeseries could look like this:

`cpu1: [1, 2, 2, 2]`
`cpu2: [1, 2, 2, null]` - last point hasn't arrived yet

Original Graphite logic is to always drop the last point, so our `movingAverage` will compute 1 from `[1, 2, 2]` for both metrics. Current Moira logic is to always consider the last point, even if it hasn't arrived yet, so our `movingAverage` will compute 2 from `[2, 2, 2]` and `[2, 2, null]`.

After some time actual value for `cpu2` arrives, and suddenly...

`cpu1: [1, 2, 2, 2]`
`cpu2: [1, 2, 2, 1]`

...Moira logic generated a false alarm for `cpu2` :(

A possible workaround is to include last bucket only if it contains a datapoint. But this is the worst option, because it shifts some metrics forward and corrupts all combining functions like `sumSeries`.

I think we should either:

1. Revert the whole commit in question.
2. Remove `+ retention` from line 134.

@gmlexx it's up to you :)

**Comment by AndrewKostousov** [comment]
I think that the best solution will be to:

1. Revert the change to original graphite engine behavior for "complex" triggers - those that operate on multiple time series (or simply put triggers with expressions containing asterisks). It is necessary because it is simply not correct to decide on whether the given threshold is crossed at the moment of the check when not all data points are received yet for this time slot.
2. Fix the current "add the last time slot" logic to be the "add the last data point if it has already arrived" logic for "simple" triggers which are computed for single time series. This change will allow Moira to still be able to issue near real time alerts in such cases.
3. Modify issued notifications to make them more specific on a matter at which exact moment the corresponding threshold was crossed. So that there would't be any confusion for anyone who will try to compare timestamps from the Moira notifications with the data points displayed by Grafana for the same expression.

**Comment by gmlexx** [comment]
It's very appreciated, that so honored minds came into discussion, but let's figure out, what is "false positive" notifications you are talking about?

Inside mentioned MovingAverage you can find three functions:
- safeAvg
- safeMin
- safeMax
All this functions by "safe" mean ignoring null values.

If you are talking about intention to use movingAverage to smooth peaks to prevent alarm fatigue, i would agree, that 3 point could become 2 points and such smoothing will not prevent alarm. But this is just a misuse of movingAverage.

@AndrewKostousov p.2 already worked as you describing. Nothing needed to change here.

@AndrewKostousov p.3 i remember the opposite problem, when graphite doesn't shows the reality as it is, because of dropping last point. Moira has an advantage here.

So, my opinion is that proposed changes are much bigger and risky, that supposed problem they should solved

**Comment by AndrewKostousov** [comment]
False positive is an alert for the trigger movingAverage(X, '3min', 'min') with the threshold = 100 for the metric that is eqaul to 200 for 2 consecutive minutes and is equal to 0 all other times.

The most annoying thing for me though is an inconsistency between Moira alerts and a graph that you see in Grafana for the metric in question. When Moira reports alert you do not see any spikes above given threshold on the graph that represents corresponding trigger expression. That really looks like a bug for me that should be fixed.

**Comment by beevee** [comment]
I think our priorities should be:

1. Consistency with Graphite in terms of calculated values. We should strive to eliminate situations when Graphite and Moira show different values for the same expression.
2. Real-timeness. We should alert users as soon as we know that something is wrong.

So, in my mind, consistency beats real-timeness, and we should revert. Or just correct one line to exclude last point.

**Comment by beevee** [comment]
@gmlexx no, p.2 doesn't hold right now. As you can see from my original example, last point is being added for `cpu2` and used for calculation as `null` even though it can receive an actual value in the future.

In this sense, Moira is inconsistent with itself, because results of calculation depend on the order of incoming datapoints. This is unacceptable.

**Comment by gmlexx** [comment]
Ok, I got it. Will it helps, if we remove last null value from calculation process? I mean non full intervals, where last point is missed will be excluded from function results.

**Comment by beevee** [comment]
@gmlexx do you propose to calculate for:

`cpu1: [1, 2, 2, 2]`
`cpu2: [1, 2, 2]` - exclude last `null`

...? Or to exclude `cpu2` entirely?

**Comment by AndrewKostousov** [comment]
This solution will only work for "simple" triggers as I proposed in p2.

It won't help in case of "complex" triggers where several time series are involved in computation since it will cause relative shift of one time series along the others.

**Comment by gmlexx** [comment]
For example, movingAverage(cpu*, 3) will calculate average for every 3 points.
For raw cpu1 [...,1,2,3,4] it will be [..., 2, 3] (no more full 3 points intervals here)
For raw cpu2 [...,1,2,3,null] it will be only [..., 2]
For raw cpu3 [...,1,2,null,4] it will be [..., 1.5, 3]

**Comment by gmlexx** [comment]
@AndrewKostousov I didn't get what time shift you a talking about.
Internally here is simple loop, that doing the same calculations for every cpuN and calculates it timestamps and value.
In case if missing last point, the last point of movingAverage results will be also missed.

**Comment by AndrewKostousov** [comment]
Items 1 and 2 of the proposed "best solution" have been implemented.
