### ISSUE TITLE
Moira cannot handle averageAbove correctly

### ISSUE THREAD

**Issue by beevee** [moira-alert/worker#9]
![2016-04-11_23-21-03](https://cloud.githubusercontent.com/assets/1009675/14437806/c4d5eefe-0044-11e6-9ea8-bb96ab284c70.png)

Graphite target on this screenshot returns only metrics that have average value above `1e-9`. In total, there are over 200 unique metrics that match this pattern. But if you look for `averageAbove` for the last hour, there are usually no more than 10 matching metrics.

Problem is, Moira remembers bad state for all 200+ metrics and shows them in ERROR state. Even when we set no data state to OK.

**Comment by gmlexx** [comment]
1) How about to remove averageAbove from target?
2) If Moira will not remember old state then every next check will have different set of metrics and there will be other bug:
Every "new metric" (that absent in previous state) will generate event NODATA -> OK, WARN or ERROR
because initial check state is NODATA.
3) Other way is to consider missed metrics from last checks as NODATA, but this will make OK status implicitly

**Comment by beevee** [comment]
This design decision is documented now: http://moira.readthedocs.org/en/latest/user_guide/efficient.html#use-graphite-functions
